### ISSUE TITLE
api `/sdapi/v1/progress` 錯誤

### ISSUE THREAD

**Issue by w-e-w** [viyiviyi/sd-encrypt-image#3]
api `/sdapi/v1/progress` 錯誤
對你沒看錯 這是issue😜
相關 https://github.com/viyiviyi/sd-encrypt-image/pull/2#issuecomment-1771028592

```shell
** API error: GET: http://127.0.0.1:55555/sdapi/v1/progress?skip_current_image=false {'error': 'TypeError', 'detail': '', 'body': '', 'errors': "argument of type 'PngInfo' is not iterable"}       | 74/150 [00:03<00:03, 19.02it/s]
    Traceback (most recent call last):
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "B:\GitHub\stable-diffusion-webui\modules\api\api.py", line 187, in exception_handling
        return await call_next(request)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "B:\GitHub\stable-diffusion-webui\modules\api\api.py", line 151, in log_and_time
        res: Response = await call_next(req)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "B:\GitHub\stable-diffusion-webui\modules\api\api.py", line 514, in progressapi
        current_image = encode_pil_to_base64(shared.state.current_image)
      File "B:\GitHub\stable-diffusion-webui\extensions\sd-encrypt-image\scripts\encrypt_image.py", line 76, in encode_pil_to_base64
        if 'Encrypt' in pnginfo and pnginfo["Encrypt"] == 'pixel_shuffle':
    TypeError: argument of type 'PngInfo' is not iterable
```

**Comment by viyiviyi** [comment]
我没能复现这个错误，但是这个错出现的原因我是知道的，这个PngInfo和Image.info果然不是一个东西。

**Comment by viyiviyi** [comment]
> api `/sdapi/v1/progress` 錯誤 對你沒看錯 這是issue😜 相關 [#2 (comment)](https://github.com/viyiviyi/sd-encrypt-image/pull/2#issuecomment-1771028592)
> 
> ```shell
> ** API error: GET: http://127.0.0.1:55555/sdapi/v1/progress?skip_current_image=false {'error': 'TypeError', 'detail': '', 'body': '', 'errors': "argument of type 'PngInfo' is not iterable"}       | 74/150 [00:03<00:03, 19.02it/s]
>     Traceback (most recent call last):
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
>         return self.receive_nowait()
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
>         raise WouldBlock
>     anyio.WouldBlock
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
>         message = await recv_stream.receive()
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
>         raise EndOfStream
>     anyio.EndOfStream
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "B:\GitHub\stable-diffusion-webui\modules\api\api.py", line 187, in exception_handling
>         return await call_next(request)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
>         raise app_exc
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
>         await self.app(scope, receive_or_disconnect, send_no_error)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
>         response = await self.dispatch_func(request, call_next)
>       File "B:\GitHub\stable-diffusion-webui\modules\api\api.py", line 151, in log_and_time
>         res: Response = await call_next(req)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
>         raise app_exc
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
>         await self.app(scope, receive_or_disconnect, send_no_error)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
>         await self.app(scope, receive, send)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
>         await responder(scope, receive, send)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
>         await self.app(scope, receive, self.send_with_gzip)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
>         raise exc
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
>         await self.app(scope, receive, sender)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
>         raise e
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
>         await self.app(scope, receive, send)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
>         await route.handle(scope, receive, send)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
>         await self.app(scope, receive, send)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
>         response = await func(request)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
>         raw_response = await run_endpoint_function(
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
>         return await run_in_threadpool(dependant.call, **values)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
>         return await anyio.to_thread.run_sync(func, *args)
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
>         return await get_asynclib().run_sync_in_worker_thread(
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
>         return await future
>       File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
>         result = context.run(func, *args)
>       File "B:\GitHub\stable-diffusion-webui\modules\api\api.py", line 514, in progressapi
>         current_image = encode_pil_to_base64(shared.state.current_image)
>       File "B:\GitHub\stable-diffusion-webui\extensions\sd-encrypt-image\scripts\encrypt_image.py", line 76, in encode_pil_to_base64
>         if 'Encrypt' in pnginfo and pnginfo["Encrypt"] == 'pixel_shuffle':
>     TypeError: argument of type 'PngInfo' is not iterable
> ```

我测试不出这个错误，但是应该是修复了。

**Comment by w-e-w** [comment]
剛剛簡單測試下 結果是沒爆炸👍 所以這個問題因該是成功修正了

但我又找到別的問題了

---

以下是在 b581376 未修正前的commit的狀況 與現在和新提的文題無關

我的操作就是在生成途中訪問了`/sdapi/v1/progress`這個API (live preview有啟動)
透過debuggerd可已看到
因為image.info 是個空的dict 所以是`PngImagePlugin.PngInfo()`
而`PngImagePlugin.PngInfo()`返回的這個東西不能當dict使用
![image](https://github.com/viyiviyi/sd-encrypt-image/assets/40751091/b1a8507c-4074-4658-8ba0-c04ac1b7e618)
原因跟你猜測的一樣
>这个PngInfo和Image.info果然不是一个东西。
